- platform: wake_on_lan
  mac: "D4-3D-7E-BA-A6-EF"
  name: Neo
  host: "192.168.1.128"
- platform: wake_on_lan
  mac: "70-8B-CD-58-66-D5"
  name: Trinity
  host: "192.168.1.250"

- platform: circadian_lighting
  name: Circadian Lighting
  lights_ct:
    - light.office_strip
#    - light.storage_light
#    - group.living_room_center_light

- platform: circadian_lighting
  name: Circadian Brightness
  lights_brightness:
    - light.bedroom_overhead_light
    - light.hallway_stairs_light
    - light.hallway_bathroom_light
    - light.hallway_laundry_light
    - group.living_room_center_light

# - platform: circadian_lighting
#   name: Circadian Sleep
#   sleep_entity:
#   sleep_state:
#   sleep_brightness: 1
#   lights_ct:
#     - light.hallway_stairs_light
#     - light.hallway_bathroom_light
#     - light.hallway_laundry_light

- platform: bhyve