- platform: universal
  name: Living Room TV
  children:
    - remote.broadlink
    - switch.tv_mute
    - input_select.living_room_tv_source
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.tv_power
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.tv_power
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.broadlink
        device: television
        command: volume_up
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.broadlink
        device: television
        command: volume_down
    volume_mute:
      service: switch.toggle
      data:
        entity_id: switch.tv_mute
    select_source:
      service: input_select.select_option
      data_template:
        entity_id: input_select.living_room_tv_source
        option: '{{ source }}'

  attributes:
    state: switch.tv_power
    is_volume_muted: switch.tv_mute
#    volume_level: media_player.MEDIA_PLAYER_NAME|volume_level
    source: input_select.living_room_tv_source
    source_list: input_select.living_room_tv_source|options