home_lights:
   name: Home Lights
   entities:
      - group.upstairs_lights
      - group.downstairs_lights
      - group.outdoor_lights
#      - group.holiday_lights

automations:
   name: Automations
   icon: mdi:playlist-check
   entities:
     - group.all_automations
     - group.all_scripts

alarmclock:
  name: Wake Up
  entities:
    - sensor.alarm_time
    - group.alarmclock_settings

alarmclock_settings:
  name: Settings
  icon: mdi:cog
  entities:
    - automation.wake_up
    - input_number.alarmhour
    - input_number.alarmminutes
    - input_boolean.alarmweekday

wmata:
  name: WMATA Info
  entities:
    - sensor.wmata_gr_no
    - sensor.wmata_gr_so
    - script.wmata_gr_no
    - script.wmata_gr_so

family:
  name: Family
  entities:
    - person.kelley
    - person.peter