- platform: history_stats
  name: Daily Heat ON time
  entity_id: sensor.hvac_status
  state: "heating"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Monthly Heat ON time
  entity_id: sensor.hvac_status
  state: "heating"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0).replace(day=1) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Daily AC ON time
  entity_id: sensor.hvac_status
  state: "cooling"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Monthly AC ON time
  entity_id: sensor.hvac_status
  state: "cooling"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0).replace(day=1) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Daily Fan ON time
  entity_id: sensor.hvac_status
  state: "fan"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Monthly Fan ON time
  entity_id: sensor.hvac_status
  state: "fan"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0).replace(day=1) }}"
  end: "{{ now() }}"
