- platform: rest
  resource: https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases_US/FeatureServer/0/query?f=json&where=(Confirmed%20%3E%200)%20AND%20(Country_Region%3D%27US%27)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Confirmed%20desc%2CCountry_Region%20asc%2CProvince_State%20asc&outSR=102100&resultOffset=0&resultRecordCount=250&cacheHint=true
  name: Corona Virus Rest
  value_template: >
    {%- set last_updated = value_json.features | map(attribute='attributes.Last_Update') | list | max / 1000 %}
    {{ last_updated | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False) }}
  json_attributes:
    - features

- platform: template
  sensors:
    coronavirus_us:
      friendly_name: Corona Virus USA
      entity_id: sensor.corona_virus_rest
      availability_template: >
        {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
        {%- set features = features | map(attribute='attributes') | list %}
        {{ features | length > 0 }}
      value_template: >
        {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
        {%- set last_updated = features | map(attribute='attributes.Last_Update') | list | max / 1000 %}
        {{ last_updated | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00') }}
      attribute_templates:
        confirmed: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {{ features | map(attribute='attributes.Confirmed') | list | sum }}
        deaths: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {{ features | map(attribute='attributes.Deaths') | list | sum }}
        recovered: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {{ features | map(attribute='attributes.Recovered') | list | sum }}
        active: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {{ features | map(attribute='attributes.Active') | list | sum }}
    coronavirus_dc:
      friendly_name: Corona Virus DC
      entity_id: sensor.corona_virus_rest
      availability_template: >
        {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
        {%- set features = features | map(attribute='attributes') | list %}
        {{ features | length > 0 }}
      value_template: >
        {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
        {%- set features = features | map(attribute='attributes') | list %}
        {%- set items = features | selectattr('Province_State','eq','District of Columbia') | list %}
        {%- if items | length > 0 %}
          {%- set item = items | first %}
          {%- set last_updated = item.Last_Update | int / 1000 %}
          {{ last_updated | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False) }}
        {%- else %}
          {{ states('sensor.coronavirus_dc') }}
        {%- endif %}
      attribute_templates:
        confirmed: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {%- set features = features | map(attribute='attributes') | list %}
          {%- set items = features | selectattr('Province_State','eq','District of Columbia') | list %}
          {%- if items | length > 0 %}
            {%- set item = items | first %}
            {{ item.Confirmed }}
          {%- else %}
            {{ state_attr('sensor.coronavirus_dc', 'confirmed') }}
          {%- endif %}
        deaths: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {%- set features = features | map(attribute='attributes') | list %}
          {%- set items = features | selectattr('Province_State','eq','District of Columbia') | list %}
          {%- if items | length > 0 %}
            {%- set item = items | first %}
            {{ item.Deaths }}
          {%- else %}
            {{ state_attr('sensor.coronavirus_dc', 'deaths') }}
          {%- endif %}
        recovered: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {%- set features = features | map(attribute='attributes') | list %}
          {%- set items = features | selectattr('Province_State','eq','District of Columbia') | list %}
          {%- if items | length > 0 %}
            {%- set item = items | first %}
            {{ item.Recovered }}
          {%- else %}
            {{ state_attr('sensor.coronavirus_dc', 'recovered') }}
          {%- endif %}
        active: >
          {%- set features = state_attr('sensor.corona_virus_rest', 'features') %}
          {%- set features = features | map(attribute='attributes') | list %}
          {%- set items = features | selectattr('Province_State','eq','District of Columbia') | list %}
          {%- if items | length > 0 %}
            {%- set item = items | first %}
            {{ item.Active }}
          {%- else %}
            {{ state_attr('sensor.coronavirus_dc', 'active') }}
          {%- endif %}