- platform: time_date
  display_options:
    - "time"
    - "date"
    - "time_utc"
    - "beat"

- platform: template
  sensors:
    alarm_time:
      friendly_name: "Time"
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'

#- platform: unifigateway
#  host: !secret unifi_host
#  port: 443
#  username: !secret unifi_un
#  password: !secret unifi_pw
#  version: UDMP-unifiOS
#  monitored_conditions:
#    - www
#    - wlan
#    - lan
#    - wan
#    - alerts
#    - firmware
