- platform: template
  sensors:
    via_destination:
      value_template: '
        {% if is_state("input_select.destination", "Peter Tysons Office") -%}
          {{ state_attr("zone.peter_tysons_office", "latitude") }},{{ state_attr("zone.peter_tysons_office", "longitude") }}
        {% elif is_state("input_select.destination", "Peter Client") -%}
          {{ state_attr("zone.peter_client", "latitude") }},{{ state_attr("zone.peter_client", "longitude") }}
        {% elif is_state("input_select.destination", "Home") -%}
          {{ state_attr("zone.home", "latitude") }},{{ state_attr("zone.home", "longitude") }}
        {% elif is_state("input_select.destination", "Gym Dupont") -%}
          {{ state_attr("zone.gym_dupont", "latitude") }},{{ state_attr("zone.gym_dupont", "longitude") }}
        {% elif is_state("input_select.destination", "Gym 14th St") -%}
          {{ state_attr("zone.gym_14th", "latitude") }},{{ state_attr("zone.gym_14th", "longitude") }}
        {%- endif %}'
    via_origin:
      value_template: '
        {% if is_state("input_select.origin", "Peter Tysons Office") -%}
          {{ state_attr("zone.peter_tysons_office", "latitude") }},{{ state_attr("zone.peter_tysons_office", "longitude") }}
        {% elif is_state("input_select.destination", "Peter Client") -%}
          {{ state_attr("zone.peter_client", "latitude") }},{{ state_attr("zone.peter_client", "longitude") }}
        {% elif is_state("input_select.origin", "Home") -%}
          {{ state_attr("zone.home", "latitude") }},{{ state_attr("zone.home", "longitude") }}
        {% elif is_state("input_select.origin", "Gym Dupont") -%}
          {{ state_attr("zone.gym_dupont", "latitude") }},{{ state_attr("zone.gym_dupont", "longitude") }}
        {% elif is_state("input_select.destination", "Gym 14th St") -%}
          {{ state_attr("zone.gym_14th", "latitude") }},{{ state_attr("zone.gym_14th", "longitude") }}
        {%- endif %}'
# - platform: google_travel_time
#   api_key: !secret google_homegraph_api
#   origin: sensor.via_origin
#   destination: sensor.via_destination
#   name: Via Driving
#   scan_interval: 21600
#   options:
#     mode: driving
#     avoid: tolls
# - platform: google_travel_time
#   api_key: !secret google_homegraph_api
#   origin: sensor.via_origin
#   destination: sensor.via_destination
#   name: Via Metro
#   scan_interval: 21600
#   options:
#     mode: transit
#     transit_mode: rail
# - platform: google_travel_time
#   api_key: !secret google_homegraph_api
#   origin: sensor.via_origin
#   destination: sensor.via_destination
#   name: Via Bus
#   scan_interval: 21600
#   options:
#     mode: transit
#     transit_mode: bus


- platform: rest
  name: "WMATA"
  resource: https://api.wmata.com/StationPrediction.svc/json/GetPrediction/E03
  method: GET
  headers:
    api_key: !secret wmata_api
  value_template: "{{ value_json.Trains[0].LocationName }}"
  json_attributes:
    - Trains
  scan_interval: 150

- platform: template
  sensors:
    wmata_gr_no:
      friendly_name: "Green Line Northbound"
      value_template: '
        {% set trains = states.sensor.wmata.attributes.Trains %}
        {% for train in trains if train.DestinationCode == "E10" %}
        {% if loop.first %}{{ train.Min }}
        {% elif loop.last %} and {{ train.Min }}
        {% else %}, {{ train.Min }},
        {% endif %}
        {% endfor %}'
      unit_of_measurement: "minutes"
    wmata_gr_so:
      friendly_name: "Green Line Southbound"
      value_template: '
        {% set trains = states.sensor.wmata.attributes.Trains %}
        {% for train in trains if train.DestinationCode == "F11" %}
        {% if loop.first %}{{ train.Min }}
        {% elif loop.last %} and {{ train.Min }}
        {% else %}, {{ train.Min }},
        {% endif %}
        {% endfor %}'
      unit_of_measurement: "minutes"
    washer_power:
      friendly_name: "Washer Power"
      value_template: "{{ state_attr('switch.washer','current_power_w') | default('0') }}"
      unit_of_measurement: "W"
      icon_template: mdi:washing-machine
    dryer_power:
      friendly_name: "Dryer Power"
      value_template: "{{ state_attr('switch.dryer','current_power_w') | default('0') }}"
      unit_of_measurement: "W"
      icon_template: mdi:tumble-dryer

- platform: seventeentrack
  username: !secret 17track_email
  password: !secret 17track_pw
