- platform: template
  sensors:
    via_destination:
      value_template: '
        {% if is_state("input_select.destination", "Peter Tysons Office") -%}
        {{ state_attr("zone.peter_tysons_office", "latitude") }},{{ state_attr("zone.peter_tysons_office", "longitude") }}
        {% elif is_state("input_select.destination", "Peter Client") -%}
        {{ state_attr("zone.peter_client", "latitude") }},{{ state_attr("zone.peter_client", "longitude") }}
        {% elif is_state("input_select.destination", "Home") -%}
        {{ state_attr("zone.home", "latitude") }},{{ state_attr("zone.home", "longitude") }}
        {% elif is_state("input_select.destination", "Gym Dupont") -%}
        {{ state_attr("zone.gym_dupont", "latitude") }},{{ state_attr("zone.gym_dupont", "longitude") }}
        {% elif is_state("input_select.destination", "Gym 14th St") -%}
        {{ state_attr("zone.gym_14th", "latitude") }},{{ state_attr("zone.gym_14th", "longitude") }}
        {%- endif %}'
    via_origin:
      value_template: '
        {% if is_state("input_select.origin", "Peter Tysons Office") -%}
        {{ state_attr("zone.peter_tysons_office", "latitude") }},{{ state_attr("zone.peter_tysons_office", "longitude") }}
        {% elif is_state("input_select.destination", "Peter Client") -%}
        {{ state_attr("zone.peter_client", "latitude") }},{{ state_attr("zone.peter_client", "longitude") }}
        {% elif is_state("input_select.origin", "Home") -%}
        {{ state_attr("zone.home", "latitude") }},{{ state_attr("zone.home", "longitude") }}
        {% elif is_state("input_select.origin", "Gym Dupont") -%}
        {{ state_attr("zone.gym_dupont", "latitude") }},{{ state_attr("zone.gym_dupont", "longitude") }}
        {% elif is_state("input_select.destination", "Gym 14th St") -%}
        {{ state_attr("zone.gym_14th", "latitude") }},{{ state_attr("zone.gym_14th", "longitude") }}
        {%- endif %}'
# - platform: google_travel_time
#   api_key: !secret google_homegraph_api
#   origin: sensor.via_origin
#   destination: sensor.via_destination
#   name: Via Driving
#   scan_interval: 21600
#   options:
#     mode: driving
#     avoid: tolls
# - platform: google_travel_time
#   api_key: !secret google_homegraph_api
#   origin: sensor.via_origin
#   destination: sensor.via_destination
#   name: Via Metro
#   scan_interval: 21600
#   options:
#     mode: transit
#     transit_mode: rail
# - platform: google_travel_time
#   api_key: !secret google_homegraph_api
#   origin: sensor.via_origin
#   destination: sensor.via_destination
#   name: Via Bus
#   scan_interval: 21600
#   options:
#     mode: transit
#     transit_mode: bus
