- platform: template
  sensors:
    smoke_alarm:
      friendly_name: "Smoke Alarm"
      device_class: smoke
      value_template: "{{ is_state('sensor.ecolink_firefighter_smoke_detector', 'detected') }}"
    co_alarm:
      friendly_name: "CO Alarm"
      device_class: safety
      value_template: "{{ is_state('sensor.ecolink_firefighter_carbon_monoxide_detector', 'detected') }}"

# - platform: template
# sensors:
# recycle:
# friendly_name: "Recycle"
# icon_template: >
# {{ state_attr('sensor.recycle', 'icon') }}
# value_template: >
# {{ state_attr('sensor.recycle', 'days') <= 1 and now().hour >= 18 }}
# trash:
# friendly_name: "Trash"
# icon_template: >
# {{ state_attr('sensor.trash', 'icon') }}
# value_template: >
# {{ state_attr('sensor.trash', 'days') <= 1 and now().hour >= 18 }}
# street_sweeping:
# friendly_name: "Street Sweeping"
# icon_template: >
# {{ state_attr('sensor.street_sweeping', 'icon') }}
# value_template: >
# {{ state_attr('sensor.street_sweeping', 'days') <= 1 and now().hour >= 18 }}

- platform: template
  sensors:
    washer_status:
      friendly_name: "Washer Cycle"
      value_template: "{{ states('sensor.washer_current_consumption')|float > 5 }}"
      icon_template: mdi:washing-machine
      delay_on:
        minutes: 5
      delay_off:
        minutes: 2
    dryer_status:
      friendly_name: "Dryer Cycle"
      value_template: "{{ states('sensor.dryer_current_consumption')|float > 5 }}"
      icon_template: mdi:tumble-dryer
      delay_on:
        minutes: 5
      delay_off:
        minutes: 1

- platform: template
  sensors:
    sleep_mode:
      friendly_name: "Sleep Mode"
      value_template: "{% if is_state('alarm_control_panel.10th_street', 'armed_home') and (now().strftime('%H:%M:%S') >= '10:00:00' or now().strftime('%H:%M:%S') <= '05:00:00')%}true{% else %}false{% endif %}"
      icon_template: "{% if is_state('sensor.sleep_mode', 'on') %}mdi:sleep{% else %}mdi:sleep-off{% endif %}"
