name: Home Assistant CI
on:
  push:
  # pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v4
      - name: Add bhyve
        run: |
          git clone https://github.com/sebr/bhyve-home-assistant.git bhyve-home-assistant/
          cp -R bhyve-home-assistant/custom_components/bhyve custom_components
          # ls custom_components/bhyve
      - name: Add circadian_lighting
        run: |
          git clone https://github.com/claytonjn/hass-circadian_lighting.git circadian_lighting/
          cp -R circadian_lighting/custom_components/circadian_lighting custom_components
          # ls custom_components/circadian_lighting
      - name: Add eufy_robovac
        run: |
          git clone https://github.com/bmccluskey/robovac.git robovac/
          cp -R robovac/custom_components/robovac custom_components
          # ls custom_components/robovac
      - name: Add eventsensor
        run: |
          git clone https://github.com/azogue/eventsensor.git eventsensor/
          cp -R eventsensor/custom_components/eventsensor custom_components
          # ls custom_components/eventsensor
      - name: Add google_home
        run: |
          git clone https://github.com/leikoilja/ha-google-home.git google_home/
          cp -R google_home/custom_components/google_home custom_components
          # ls custom_components/google_home
      - name: Add HACS
        run: |
          git clone https://github.com/hacs/integration.git hacs/
          cp -R hacs/custom_components/hacs custom_components
          # ls custom_components/hacs
      - name: Add unifigateway
        run: |
          git clone https://github.com/custom-components/sensor.unifigateway.git unifigateway/
          cp -R unifigateway/custom_components/unifigateway custom_components
          # ls custom_components/unifigateway
      - name: List Custom Components
        run: ls custom_components
      - name: Add Dummy Zones
        run: cp ./travis/travis_zones.yaml zones.yaml
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.4
        with:
          secrets: ./travis/travis_secrets.yaml
          version: "${{ matrix.version }}"
